<?php
/**
 * @var Lopatin\Faq\Block\Display $block
 */
//var_dump($block::whoAreYou());
?>
<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
        margin-top: 30px;
    }

    td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }

    .post-id {
        width: 2%
    }

    .post-name {
        width: 30%
    }

</style>

<table>
    <tr>
        <th class="post-id">Id</th>
        <th class="post-name">Name</th>
        <th>Question</th>
        <th>Answer</th>
        <th>Date</th>
        <th>Status</th>
    </tr>
    <?php
    foreach ($block->getFaqCollection() as $key => $post) {
        echo '<tr>
                    <td>' . $post->getPostId() . '</td>
                    <td>' . $post->getName() . '</td>
                    <td>' . $post->getQuestion() . '</td>
                    <td>' . $post->getAnswer() . '</td>
                    <td>' . $post->getCreatedAt() . '</td>
                    <td>' . $post->getStatus() . '</td>
                  </tr>';
    }
    ?>
</table>

</body>
</html>
